CREATE TRIGGER [Trigger]
	ON [dbo].[MEMBROS]
	FOR DELETE, INSERT, UPDATE
	AS
	BEGIN
		SET NOCOUNT ON

		SET IDENTITY_INSERT [dbo].[MEMBROS] ON
INSERT INTO [dbo].[MEMBROS] ([Id_MEMBRO], [NOME], [CPF], [RG], [DATA_NASCIMENTO], [NOME_DA_MAE], [TELEFONE], [EMAIL], [ESTADO], [CIDADE], [ENDERECO], [CEP], [NUM_RESIDENCIA], [GRAU_ESCOLAR], [NUMERO_PESSOAS], [RENDA_FAMILIAR], [TIPO_DEFICIENCIA], [TIPO_DOENCA]) VALUES 
(1, 'JEFERSON', 12312312312, 121231231, 21/09/1999, 'Gildete', 11998897550, 'a@a.com', 'Sao Paulo', 'SP', 'Jardim Amalia', 05890000, 100, 'Ensino Medio Completo', 4, 5000)
SET IDENTITY_INSERT [dbo].[MEMBROS] on



	END


